version: "3"

networks:
  front:
    driver: bridge
  db:
    driver: bridge

services:
  mysql:
    image: mysql:5.7.12
    command: --character-set-server=utf8mb4
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - db

  migration:
    depends_on: [mysql]
    image: mcr.microsoft.com/dotnet/core/sdk:3.1-bionic
    entrypoint: ./migration.sh
    working_dir: /sandbox/WebApp
    volumes:
      - ./WebApp/:/sandbox/WebApp/
      - ./EchoMagicOnion.Shared/:/sandbox/EchoMagicOnion.Shared/
      - ../src/DFRame/:/src/DFrame/
      - ../src/DFrame.ComponentLibrary/:/src/DFrame.ComponentLibrary/
      - ../src/DFrame.Hosting/:/src/DFrame.Hosting/
      - ../src/DFrame.LoadTesting/:/src/DFrame.LoadTesting/
      - ../src/DFrame.Profiler/:/src/DFrame.Profiler/
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    networks:
      - db
