namespace: dframe
bases:
  - ../../base

resources:
  - namespace.yaml
  - role.yaml
  - rolebinding.yaml
  - service.yaml
  - serviceaccount.yaml

patches:
  # - deployment.yaml
  - job.yaml
  # - job_args.yaml
  # - pod.yaml
