version: "3"

services:
  # access http://localhost:8089 for web ui
  master:
    depends_on: [worker]
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./:/mnt/locust
    #command: -f /mnt/locust/locustfile.py --master -H http://host.docker.internal:5000 --headless -u 500 -r 500
    command: -f /mnt/locust/locustfile.py --master -H http://host.docker.internal:5000

  worker:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master
