apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dframe-master
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: ["extensions", "apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: ["extensions", "batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "delete"]
