apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dframe-master
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dframe-master
subjects:
  - kind: ServiceAccount
    name: dframe-master
    namespace: dframe
