apiVersion: apps/v1
kind: Deployment
metadata:
  name: dframe-master
spec:
  template:
    spec:
      imagePullSecrets:
        - name: aws-registry
      containers:
        - name: dframe-master
          env:
            - name: WORKER_IMAGE_PULL_SECRET
              value: "aws-registry"
            - name: WORKER_IMAGE_PULL_POLICY
              value: "Never"
