apiVersion: apps/v1
kind: Deployment
metadata:
  name: dframe-master
spec:
  template:
    spec:
      serviceAccountName: dframe-master
      nodeSelector:
        eks.amazonaws.com/nodegroup: dframe
