apiVersion: batch/v1
kind: Job
metadata:
  name: dframe-master
spec:
  template:
    spec:
      serviceAccountName: dframe-master
      nodeSelector:
        eks.amazonaws.com/nodegroup: dframe
      containers:
        - name: dframe-master
          env:
            - name: DFRAME_MASTER_CONNECT_TO_HOST
              value: "dframe-master.dframe.svc.cluster.local"
            - name: DFRAME_WORKER_IMAGE_NAME
              value: 431046970529.dkr.ecr.ap-northeast-1.amazonaws.com/dframe-k8s
            - name: DFRAME_WORKER_IMAGE_TAG
              value: "0.1.0"
