name: (R) build-unity

on:
  workflow_call:
    inputs:
      ref:
        description: "github ref to build"
        required: false
        type: string
        default: ""
      version:
        description: "build artifact version."
        required: false
        type: string
        default: ""

jobs:
  build-unity:
    strategy:
      matrix:
        unity: ["2020.3.29f1"]
        include:
          - unity: 2020.3.29f1
            license: UNITY_LICENSE_2020
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Configure Environment Variables
        run: |
          echo "CHECKOUT_REF=${{ inputs.ref }}" | tee -a "$GITHUB_ENV"
          echo "VERSION=${{ inputs.version != '' && inputs.version || matrix.unity }}" | tee -a "$GITHUB_ENV"

      - name: Showing checkout ref
        run: echo "${{ env.CHECKOUT_REF }}"
      - uses: actions/checkout@v3
        with:
          ref: ${{ env.CHECKOUT_REF }}

      # Execute scripts: Export Package
      #  /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -projectPath . -executeMethod PackageExporter.Export
      - name: Export unitypackage
        uses: game-ci/unity-builder@v2.0-alpha-6
        env:
          UNITY_LICENSE: ${{ secrets[matrix.license] }}
        with:
          projectPath: src/DFrame.Unity
          unityVersion: ${{ matrix.unity }}
          targetPlatform: StandaloneLinux64
          buildMethod: PackageExporter.Export
          versioning: None

      - name: check all .meta is commited
        run: |
          if git ls-files --others --exclude-standard -t | grep --regexp='[.]meta$'; then
            echo "Detected .meta file generated. Do you forgot commit a .meta file?"
            exit 1
          else
            echo "Great, all .meta files are commited."
          fi
        working-directory: src/DFrame.Unity

      # Store artifacts.
      - uses: actions/upload-artifact@v2
        with:
          name: DFrame.Unity.${{ env.VERSION }}.unitypackage
          path: ./src/DFrame.Unity/*.unitypackage
