name: Build-Debug

on:
  push:
    branches:
      - "**"
    tags:
      - "!*" # not a tag push
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build-dotnet:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      NUGET_XMLDOC_MODE: skip
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.201
      # build src
      - run: dotnet build -c Debug ./src/DFrame
      - run: dotnet build -c Debug ./src/DFrame.Kubernetes
      - run: dotnet build -c Debug ./src/DFrame.LoadTesting
      - run: dotnet build -c Debug ./src/DFrame.OutOfProcess
      - run: dotnet build -c Debug ./src/DFrame.Hosting
      - run: dotnet build -c Debug ./src/DFrame.ComponentLibrary
      # build sandbox
      - run: dotnet build -c Debug ./sandbox/ConsoleApp
      - run: dotnet build -c Debug ./sandbox/ConsoleAppK8s
      - run: dotnet build -c Debug ./sandbox/WebApp
      # tests
      #- run: dotnet test -c Debug --no-build ./tests/DFrame.Tests/DFrame.Tests.csproj
