name: Build-Canary

on:
  push:
    branches:
      - "master"
    tags:
      - "!*" # not a tag push

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  NUGET_XMLDOC_MODE: skip
  DOTNET_VERSION: '6.0.x'
  DISABLE_NETFX_TARGET_BUILD: 1

jobs:
  canary-build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - run: echo "BUILD_VERSION=ci-$(date '+%Y%m%d-%H%M%S')+${GITHUB_SHA:0:6}" | tee -a $GITHUB_ENV
      - run: dotnet build -c Release -p:VersionSuffix=${BUILD_VERSION}

      - run: dotnet pack ./src/DFrame/DFrame.csproj -c Release --no-build -p:VersionSuffix=${BUILD_VERSION} -o ./publish
      - run: dotnet pack ./src/DFrame.LoadTesting/DFrame.LoadTesting.csproj -c Release --no-build -p:VersionSuffix=${BUILD_VERSION} -o ./publish
      - run: dotnet pack ./src/DFrame.OutOfProcess/DFrame.OutOfProcess.csproj -c Release --no-build -p:VersionSuffix=${BUILD_VERSION} -o ./publish
      - run: dotnet pack ./src/DFrame.Kubernetes/DFrame.Kubernetes.csproj -c Release --no-build -p:VersionSuffix=${BUILD_VERSION} -o ./publish
      - run: dotnet pack ./src/DFrame.Ecs/DFrame.Ecs.csproj -c Release --no-build -p:VersionSuffix=${BUILD_VERSION} -o ./publish

      - uses: actions/upload-artifact@v1
        with:
          name: nuget
          path: ./publish/

  canary-push:
    needs: [canary-build]
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      NUGET_CREDENTIALPROVIDER_SESSIONTOKENCACHE_ENABLED: true
    steps:
      - uses: actions/download-artifact@v2
      # Upload to NuGet
      - run: echo "VSS_NUGET_EXTERNAL_FEED_ENDPOINTS=${FEED_ENDPOINTS}" >> $GITHUB_ENV
        env:
          FEED_ENDPOINTS: ${{ secrets.VSS_NUGET_EXTERNAL_FEED_ENDPOINTS_PUBLIC_CANARY }}
      - run: wget -qO- https://raw.githubusercontent.com/Microsoft/artifacts-credprovider/master/helpers/installcredprovider.sh | bash
      - run: dotnet nuget push "./nuget/*.nupkg" --skip-duplicate -s https://pkgs.dev.azure.com/cysharp/Public/_packaging/Canary-Build/nuget/v2 -k AzureDevOps
