name: Build-Release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

jobs:
  build-dotnet:
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      NUGET_XMLDOC_MODE: skip
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.201
      # set release tag(*.*.*) to env.GIT_TAG
      - run: echo ::set-env name=GIT_TAG::${GITHUB_REF#refs/tags/}

      # build and test
      - run: dotnet build -c Release -p:Version=${{ env.GIT_TAG }}
      # - run: dotnet test -c Release --no-build

      # pack packages
      - run: dotnet pack ./src/DFrame/DFrame.csproj -c Release --no-build -p:Version=${{ env.GIT_TAG }}
      - run: dotnet pack ./src/DFrame.LoadTesting/DFrame.LoadTesting.csproj -c Release --no-build -p:Version=${{ env.GIT_TAG }}
      - run: dotnet pack ./src/DFrame.OutOfProcess/DFrame.OutOfProcess.csproj -c Release --no-build -p:Version=${{ env.GIT_TAG }}
      - run: dotnet pack ./src/DFrame.Kubernetes/DFrame.Kubernetes.csproj -c Release --no-build -p:Version=${{ env.GIT_TAG }}

      # Upload to NuGet
      - run: dotnet nuget push "./src/DFrame/bin/Release/*.nupkg" -s https://www.nuget.org/api/v2/package -k ${{ secrets.NUGET_KEY }}
      - run: dotnet nuget push "./src/DFrame.LoadTesting/bin/Release/*.nupkg" -s https://www.nuget.org/api/v2/package -k ${{ secrets.NUGET_KEY }}
      - run: dotnet nuget push "./src/DFrame.OutOfProcess/bin/Release/*.nupkg" -s https://www.nuget.org/api/v2/package -k ${{ secrets.NUGET_KEY }}
      - run: dotnet nuget push "./src/DFrame.Kubernetes/bin/Release/*.nupkg" -s https://www.nuget.org/api/v2/package -k ${{ secrets.NUGET_KEY }}