name: Build-Debug

on:
  workflow_dispatch:
  push:
    branches:
      - "master"
    tags:
      - "!*" # not a tag push
  pull_request:
    branches:
      - master

jobs:
  build-dotnet:
    uses: ./.github/workflows/_build-dotnet.yaml

  build-unity:
    if: "((github.event_name == 'push' && github.repository_owner == 'Cysharp') || startsWith(github.event.pull_request.head.label, 'Cysharp:'))"
    uses: ./.github/workflows/_build-unity.yaml
