apiVersion: apps/v1
kind: Deployment
metadata:
  name: magiconion
  labels:
    app: magiconion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: magiconion
  template:
    metadata:
      labels:
        app: magiconion
    spec:
      containers:
        - name: magiconion
          image: cysharp/dframe-magiconion:0.4.0
          imagePullPolicy: Always
          ports:
            - name: grpc
              containerPort: 12346
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 2000m
              memory: 1000Mi
